name: mamscorner
favicon: null
layout_spectrum: 0.8511464302428067
typography_spectrum: 0.75829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebce82'
    - '#814523'
    - '#937647'
    - '#6cc9df'
    - '#0396c2'
  brandStrength: 0.9849399079103023
  lightness: 0.056278239004313946
  saturation: 0.5769971129484475
  rhythmicContrast: 0.46086059254594147
purpose: []
